### PR TITLE
Fixed make github-release and added tests

### LINKED ISSUE #1355: Fix override number for make github-release
**What would you like to be added**:
A previous change removed the override number option from Release because it was thought this was not needed and the code implementing this a mess. But the `make github-release` command still needed this value and it broke without it. (FOLLOW UP: make docs isn't broken but it does need this feature added to it. See ticket https://github.com/aws/eks-distro/issues/1354)

**Why is this needed**:
I broke things.

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*
closes #1355

*Description of changes:*
* Changes to Release
  * Moved Release to it's own directory, which is why it looks new
  * Added override number option when creating Release (DO NOT USE THIS IN MOST CASES)
  * Created releaseinput.go to handle internal logic of creating Release
  * Created tests for Release
* Added override number option to github-release

*Confirmation that it worked* 
* `RELEASE_BRANCH=1-20 OVERRIDE_NUMBER=21 make github-release` generated this https://github.com/aws/eks-distro/releases/tag/v1-20-eks-21
* `RELEASE_BRANCH=1-21 make github-release` generated this https://github.com/aws/eks-distro/releases/tag/v1-21-eks-19

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: cmd/release/gh-release/main.go [hunk 1]
```diff
@@ -26,18 +26,30 @@ var (
 // TODO: implement number override for release
 func main() {
 	branch := flag.String("branch", "", "Release branch, e.g. 1-22")
+	overrideNumber := flag.String("overrideNumber", "", "Optional override number, e.g. 1")
```
Comment (markapruett) [inline cmd/release/gh-release/main.go:29]: Should this be named something like "override version" to distinguish that it is a string and not a number?

Comment (kschumy) [reply cmd/release/gh-release/main.go:29]: Release number is an established thing throughout the code and release process. I would be hesitant to change this to version because I can imagine that there would be confusion between this and Kubernetes version.

File: Makefile [hunk 2]
```diff
@@ -217,7 +218,7 @@ release-docs:
 
 .PHONY: github-release
 github-release:
-	go vet ./cmd/release/github_release
-	go run ./cmd/release/github_release/main.go \
+	go vet ./cmd/release/gh-release
+	go run ./cmd/release/gh-release/main.go \
 		--branch=$(RELEASE_BRANCH) \
-		--number=$(PROD_RELEASE)
```
[the remark this answers is not in the document]
Comment (kschumy) [reply Makefile:223]: It was a thing before the major refactor: https://github.com/aws/eks-distro/pull/1242 

I had removed it because I didn't think we needed it, and the original implementation I did of it was bad. It allowed for way to much flexibility and the logic to deal with all this flexibility was a nightmare to navigate through and maintain
